name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # or master depending on your repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # Since your index.html is in the root
          publish_branch: gh-pages
          force_orphan: true  # this creates the branch without history to avoid git issues
